#!/usr/bin/env python3
"""Enumerate a change set and flag lines that likely carry personal scaffolding.

Usage:
  scan_changeset.py staged            # git diff --cached
  scan_changeset.py working           # git diff
  scan_changeset.py <commit-hash>     # that commit's changes
  scan_changeset.py <A>..<B>          # a range

Add a repo path as a second argument to scan a repo other than the current
directory: `scan_changeset.py staged /path/to/repo`. Without it, git runs in
the current directory — so make sure you're in the repo you mean to scrub.

Prints JSON: for each file, the new-file line numbers the change added, and any
lines matching reference patterns (bead ids, ticket ids, local doc refs, agent
chatter). The line numbers are the fence — edits belong only within them. The
flags are candidates, not verdicts; the comment-quality call is the model's.
"""
import json
import re
import subprocess
import sys

# Reference patterns. Deliberately loose — surfacing a false positive costs a
# glance; missing one lets scaffolding through. The model decides what to cut.
PATTERNS = {
    "bead": re.compile(r"\b(?:sl|bd|beads?)-[0-9a-z]{3,}\b|\bbeads?\b", re.I),
    "ticket": re.compile(r"\b[A-Z]{2,}-\d+\b"),
    "local_doc": re.compile(r"\b[\w./-]+\.(?:md|txt|rst)\b", re.I),
    "chatter": re.compile(
        r"\bas requested\b|\bas you (?:asked|requested|wanted)\b"
        r"|\bper your\b|\bper the (?:plan|bead|spec|ticket)\b"
        r"|\bI(?:'ve| have| )?(?:added|changed|updated|created|removed|refactored)\b"
        r"|\bNote:\s*I\b|\bTODO\([^)]*\)|\bgenerated by\b|\bClaude\b",
        re.I,
    ),
}

HUNK = re.compile(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@")


def diff_command(target, repo):
    c = ["git", "-C", repo] if repo else ["git"]
    if target == "staged":
        return c + ["diff", "--cached", "-U0"]
    if target == "working":
        return c + ["diff", "-U0"]
    if ".." in target:
        return c + ["diff", "-U0", target]
    # A single commit hash.
    return c + ["show", "-U0", "--format=", target]


def parse(diff_text):
    files = {}
    path = None
    new_ln = 0
    for line in diff_text.splitlines():
        if line.startswith("+++ "):
            raw = line[4:].strip()
            path = raw[2:] if raw.startswith("b/") else raw
            if path == "/dev/null":
                path = None
            elif path not in files:
                files[path] = {"added_lines": [], "flags": []}
            continue
        m = HUNK.match(line)
        if m:
            new_ln = int(m.group(1))
            continue
        if path is None:
            continue
        if line.startswith("+") and not line.startswith("+++"):
            content = line[1:]
            files[path]["added_lines"].append(new_ln)
            hits = sorted(k for k, p in PATTERNS.items() if p.search(content))
            if hits:
                files[path]["flags"].append(
                    {"line": new_ln, "kinds": hits, "text": content.rstrip()}
                )
            new_ln += 1
    return files


def main():
    if len(sys.argv) not in (2, 3):
        print(__doc__.strip(), file=sys.stderr)
        sys.exit(2)
    target = sys.argv[1]
    repo = sys.argv[2] if len(sys.argv) == 3 else None
    try:
        out = subprocess.run(
            diff_command(target, repo), capture_output=True, text=True, check=True
        ).stdout
    except subprocess.CalledProcessError as e:
        print(f"git failed: {e.stderr.strip()}", file=sys.stderr)
        sys.exit(1)

    files = parse(out)
    total_flags = sum(len(f["flags"]) for f in files.values())
    print(
        json.dumps(
            {
                "target": target,
                "file_count": len(files),
                "flag_count": total_flags,
                "files": files,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
